services:
  db:
    image: postgres:16
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - kanban_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d kanban" ]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - kanban-net

  backend:
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=kanban;Username=user;Password=password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kanban-net

  frontend:
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5000
    ports:
      - "127.0.0.1:3000:80"

volumes:
  kanban_data:


networks:
  kanban-net:
    driver: bridge
